[package]
authors = ["Przemyslaw M. Maciolek <pmm@collective-sense.com>"]
name = "hyena"
version = "0.1.0"

[dependencies]
bincode = "0.8.0"
nanomsg = "0.6.2"
rand = "0.3"
serde = "1.0.7"
serde_derive = "1.0.6"
